### ISSUE TITLE
Does not work at all for me 

### ISSUE THREAD

**Issue by Mxesli** [Microsoft/PowerBI-visuals-sampleUsingExternalLibraries#3]
I have jquery installed global on this pc but i still wont compile at all 

Error code:
```
 error  UNKNOWN { Error: ENOENT: no such file or directory, stat 'C:\Work\PowerBI\PowerBI-visuals-sampleUsingExternalLibraries-master\node_modules\jquery\dist\jquery.js'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (C:\Users\philipps\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\graceful-fs\polyfills.js:297:22)
    at Object.copySync (C:\Users\philipps\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\fs-extra\lib\copy-sync\copy-sync.js:21:84)
    at files.map.file (C:\Users\philipps\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:185:12)
    at Array.map (<anonymous>)
    at copyPackageFilesWithNamespace (C:\Users\philipps\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:166:18)
    at Promise (C:\Users\philipps\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:247:28)
    at new Promise (<anonymous>)
    at Function.build (C:\Users\philipps\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:244:16)
    at _validateApiVersion.then.then (C:\Users\philipps\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\VisualBuilder.js:101:44)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Work\\PowerBI\\PowerBI-visuals-sampleUsingExternalLibraries-master\\node_modules\\jquery\\dist\\jquery.js' }
```

**Comment by ignatvilesov** [comment]
Did you execute `npm install` before building the project?

**Comment by Mxesli** [comment]
yes. i did npm install -g jquery and after that npm install --save jquery

**Comment by ignatvilesov** [comment]
There's no need to install dependencies globally. All of dependencies must be installed locally instead.
Please execute `npm install` without `-g` flag.
